## Nightly-only features
# binop_separator = "Front"
# blank_lines_lower_bound = 0
# blank_lines_upper_bound = 1
# brace_style = "SameLineWhere"
# color = "Auto"
# combine_control_expr = true
# comment_width = 80
# condense_wildcard_suffixes = false
# control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
# edition = "2018"
# emit_mode = "Files"
# empty_item_single_line = true
# enum_discrim_align_threshold = 0
# error_on_line_overflow = false
# error_on_unformatted = false
# fn_args_density = "Tall"
# fn_single_line = false
# force_multiline_blocks = false
# format_doc_comments = true
# format_macro_bodies = true
# format_macro_matchers = true
# format_strings = true
# hide_parse_errors = false
# ignore = []
# imports_indent = "Block"
# imports_layout = "Mixed"
# indent_style = "Block"
# license_template_path = "LICENSE_TEMPLATE"
# make_backup = false
# match_arm_blocks = true
# match_block_trailing_comma = false
# merge_imports = true
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = false
# report_fixme = "Never"
# report_todo = "Never"
# required_version = "1.0.0"
# skip_children = false
# space_after_colon = true
# space_before_colon = false
# spaces_around_ranges = false
# struct_field_align_threshold = 0
# struct_lit_single_line = true
# trailing_comma = "Vertical"
# trailing_semicolon = true
# type_punctuation_density = "Wide"
# unstable_features = true
# where_single_line = false
# wrap_comments = true

## Stable features
force_explicit_abi = true
hard_tabs = false
max_width = 100
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
